spring:
  profiles:
    active: "dev"
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

---
#spring dev profile
spring:
  profiles: dev
  thymeleaf:
    cache: false
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8000

google:
   map:   
      api:
         endpoint: https4://maps.googleapis.com/maps/api/geocode/xml?
         key: AIzaSyBXTvljqELfjPalHuT5PHDk-qz5xnIw3VI

---

#spring production profile
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/hbb
    username: root
    password:
    dbcp2:
      test-while-idle: true
      validation-query: select 1
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8000

---
